#!/usr/bin/env node

// --git-dir=${inputDir}/.git --work-tree=${inputDir}
// rev-parse HEAD
// describe --tags
require('sywac')
  .dir('--git-dir <dir>', { mustExist: true })
  .dir('--work-tree <dir>', { mustExist: true })
  .outputSettings({ showHelpOnError: false })
  .parseAndExit()
  .then(argv => {
    console.log(argv._[0] === 'describe' ? 'v2.0.1-12-g0123456' : '0123456789abcdef0123456789abcdef01234567')
  })
